[versions]
agp = "9.2.1"
coreKtx = "1.16.0"
activity = "1.13.0"
libvlc = "3.7.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
libvlc = { group = "org.videolan.android", name = "libvlc-all", version.ref = "libvlc" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
